spring:
  profiles:
    active: dev
---
server:
  port: 16001
spring:
  profiles: dev
  application:
    name: rabb-dev-change3
---
server:
  port: 16001
spring:
  profiles: test
  application:
    name: rabb-test
---
server:
  port: 16001
spring:
  profiles: prod
  application:
    name: rabb-prod
